name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Tes Bilangan Positif/Negatif
      id: tes-bilangan-positif-negatif
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Tes Bilangan Positif/Negatif
        setup-command: ''
        command: test.sh
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TES-BILANGAN-POSITIF-NEGATIF_RESULTS: "${{steps.tes-bilangan-positif-negatif.outputs.result}}"
      with:
        runners: tes-bilangan-positif-negatif
